export const novelExercises = {
    chapter1: [
      "Where does Pip encounter the convict for the first time?",
      "What was Pip doing at the graveyard?",
      "How does the convict threaten Pip?",
      "What does the convict ask Pip to bring him?",
      "How does Pip feel after meeting the convict?",
      "Who is Mrs. Joe Gargery in Pip's life?",
      "What was the weather like in the first chapter?",
      "Why is Pip scared to tell anyone about the convict?",
      "How is Pip’s relationship with Joe Gargery shown?",
      "What emotions dominate Pip’s mind in this chapter?",
    ],
    chapter2: [
      "How does Pip describe his sister, Mrs. Joe?",
      "What kind of upbringing does Pip receive from Mrs. Joe?",
      "Who is Joe Gargery, and what is his profession?",
      "How does Pip plan to help the convict without being caught?",
      "What does Pip steal from the house for the convict?",
      "What is Pip’s internal conflict in this chapter?",
      "How is Joe’s character different from Mrs. Joe’s?",
      "What does Pip feel guilty about?",
      "What is Mrs. Joe preparing in the kitchen?",
      "Why does Pip think he might be caught?",
    ],
    chapter3: [
      "How does Pip deliver the stolen goods to the convict?",
      "What is the convict’s reaction when he receives the food and file?",
      "Who does Pip meet during his journey to the marshes?",
      "How is the relationship between the two convicts described?",
      "How does Pip feel about helping the convict?",
      "What promise does Pip make to the convict?",
      "What is Pip’s biggest fear while sneaking food?",
      "Why does Pip think the convict is somehow kind to him?",
      "What does the second convict look like?",
      "What setting details create tension during Pip’s visit?",
    ],
    chapter4: [
      "What preparations are made for Christmas dinner at Pip’s home?",
      "How do Pip’s feelings of guilt show during dinner?",
      "Who visits Pip’s house on Christmas Day?",
      "How does the police sergeant's arrival create tension?",
      "What does Pip expect when the police come?",
      "How does Pip imagine being caught?",
      "How is Joe’s behavior toward Pip different from Mrs. Joe’s?",
      "What tools are missing from Joe’s forge?",
      "How is the stolen food discovered (or not)?",
      "Why is Pip terrified during the meal?",
    ],
    chapter5: [
      "What do the soldiers reveal they need from Joe Gargery?",
      "How does Pip feel seeing the soldiers at the house?",
      "What is the outcome of the soldiers’ search?",
      "What happens when Pip sees the two convicts again?",
      "How does the convict protect Pip?",
      "How does Pip describe the marshes during the search?",
      "What is Joe’s attitude toward helping the soldiers?",
      "What does Pip learn about human kindness from this event?",
      "Why does Pip feel relief at the convict’s actions?",
      "How does the weather contribute to the suspense?",
    ],
    chapter6: [
      "What happens after the convicts are captured?",
      "How does Pip’s conscience react to recent events?",
      "What advice does Joe give Pip?",
      "How does Pip view himself after helping the convict?",
      "What role does guilt play in Pip’s thoughts?",
      "How does Pip’s fear of discovery slowly decrease?",
      "Why is Pip unable to confess to Mrs. Joe or Joe?",
      "How is Joe’s kindness highlighted again?",
      "How does Pip begin to see the difference between right and wrong?",
      "What major internal change happens in Pip?",
    ],
    chapter7: [
      "What is Pip’s education like under Mr. Wopsle’s great-aunt?",
      "Who is Biddy, and how does she help Pip?",
      "How does Pip feel about his social position?",
      "What is Pip’s first real ambition?",
      "How does Pip view Joe’s simple, honest lifestyle?",
      "What does Pip realize about intelligence and status?",
      "How does Pip describe his visits to the school?",
      "Why does Pip begin to feel ashamed of his background?",
      "How is Joe’s illiteracy presented?",
      "What dream does Pip start to develop?",
    ],
    chapter8: [
      "Who invites Pip to Satis House?",
      "How is Miss Havisham described?",
      "What impression does Estella make on Pip?",
      "How does Estella insult Pip?",
      "Why does Pip feel humiliated at Satis House?",
      "What strange things does Pip notice about Miss Havisham’s house?",
      "How does Pip react to Estella’s behavior?",
      "What is the meaning of Miss Havisham’s appearance?",
      "How does Pip’s visit change his view of himself?",
      "What does Pip wish for after visiting Satis House?",
    ],
    chapter9: [
      "What story does Pip tell Mrs. Joe and Pumblechook about Satis House?",
      "Why does Pip lie about Miss Havisham’s house?",
      "How does Joe react to Pip’s lying?",
      "What lesson does Joe try to teach Pip about being 'common'?",
      "Why does Pip feel dissatisfied with his life?",
      "How does Pip’s view of Joe change after visiting Satis House?",
      "What does Pip realize about truth and pride?",
      "How is Joe’s honesty contrasted with Pip’s shame?",
      "How does Biddy support Pip’s emotional struggles?",
      "What promise does Pip make to himself?",
    ],
    chapter10: [
      "Where does Pip meet the mysterious stranger?",
      "What is suspicious about the stranger’s conversation?",
      "What is the significance of the file the stranger uses?",
      "How does Pip feel about the stranger’s visit?",
      "Why does Pip feel increasingly uncomfortable?",
      "What gift does the stranger leave Pip?",
      "How does Pip react to receiving money?",
      "What is Joe’s reaction to the stranger’s behavior?",
      "How does Pip begin to link past events with current mysteries?",
      "How does fear affect Pip’s behavior again?",
    ],
    chapter11: [
      "Who does Pip meet again at Satis House?",
      "What new experiences does Pip have during his visit?",
      "How does Miss Havisham continue to manipulate Pip?",
      "What role does Estella play in Pip’s feelings?",
      "What happens during Pip’s fight with the pale young gentleman?",
      "How does Pip feel about winning the fight?",
      "How does Miss Havisham reward Pip?",
      "What is the symbolism of Miss Havisham’s house?",
      "What emotions dominate Pip during this visit?",
      "How does Pip’s ambition strengthen after Satis House?",
    ],
    chapter12: [
      "Why does Pip continue to visit Miss Havisham?",
      "What tasks does Pip perform at Satis House?",
      "How does Estella’s behavior affect Pip?",
      "What hope does Pip develop regarding Estella?",
      "Why does Pip feel torn between his home life and Satis House?",
      "How does Miss Havisham encourage Pip’s emotions?",
      "What new opportunities does Pip dream of?",
      "How does Pip’s relationship with Joe become strained?",
      "What causes Pip to feel embarrassed by Joe?",
      "How does Pip’s desire for a better life start to grow stronger?",
    ],
    general: [
      "Describe Pip’s journey from a poor boy to a gentleman.",
      "How does Joe Gargery serve as a father figure for Pip?",
      "What lessons does Pip learn about loyalty and humility?",
      "How does social class affect Pip’s character?",
      "Analyze Estella’s role in Pip’s emotional growth.",
      "How is Miss Havisham’s bitterness portrayed through her actions?",
      "What themes of ambition and regret are present in the novel?",
      "Compare Pip’s attitude at the start and end of the novel.",
      "How does Dickens use setting to create atmosphere in the novel?",
      "What does Pip realize about true greatness by the end of the story?",
    ]
  };
  